formats:
  - pdf
  - epub
  
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
   install:
     - requirements: docs/requirements.txt

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py